import json
import requests
import config
from typing import Tuple

def analyze_email(sender: str, subject: str, body: str) -> Tuple[str, float, str]:
    """Analyzes an email for phishing using the Ollama API.
    
    Reads config.OLLAMA_URL and config.OLLAMA_MODEL.
    Sends a POST request to {OLLAMA_URL}/api/generate.
    
    Returns:
        A tuple of (verdict, confidence, reason).
        On any exception or failure, returns ("UNKNOWN", 0.0, "parse error").
    """
    url = f"{config.OLLAMA_URL.rstrip('/')}/api/generate"
    
    prompt = (
        "You are a phishing email detector. Classify the following email strictly as PHISHING or SAFE. "
        "Respond in JSON with three fields: verdict (PHISHING or SAFE), confidence (float 0.0 to 1.0), "
        "reason (one sentence explanation). "
        f"Email details — From: {sender}, Subject: {subject}, Body: {body}"
    )
    
    payload = {
        "model": config.OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False,
        "format": "json"
    }
    
    try:
        # We set a reasonable timeout (e.g., 60 seconds) because LLM inference can take some time
        response = requests.post(url, json=payload, timeout=60)
        response.raise_for_status()
        
        # Parse the main response JSON from Ollama API
        response_json = response.json()
        model_response_str = response_json.get("response", "")
        
        # Parse the inner JSON generated by the model
        model_data = json.loads(model_response_str)
        
        verdict = model_data.get("verdict", "UNKNOWN")
        confidence = float(model_data.get("confidence", 0.0))
        reason = model_data.get("reason", "parse error")
        
        # Normalize/validate verdict
        if verdict not in ("PHISHING", "SAFE"):
            verdict = "UNKNOWN"
            
        return verdict, confidence, reason
    except Exception:
        return "UNKNOWN", 0.0, "parse error"
